server:
  port: 8190
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

home-dash:
  homeDir: ${user.dir}/data
  useMysql: false
  mysql:
    url: jdbc:mysql://localhost:3306/home_dash
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

