CREATE SCHEMA home_dash AUTHORIZATION home_dash;

CREATE TABLE file (
  id bigint NOT NULL generated by default as identity,
  file_name varchar(100) NOT NULL,
  parent_id bigint NOT NULL DEFAULT 0,
  type varchar(45) NOT NULL,
  size bigint DEFAULT 0,
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  resource_id bigint DEFAULT NULL,
  constraint home_dash_file_id_key PRIMARY KEY (id));

CREATE INDEX index2 ON file(parent_id, file_name);

CREATE TABLE resource (
  id bigint NOT NULL generated by default as identity,
  size bigint DEFAULT 0,
  md5 varchar(32) DEFAULT '',
  path varchar(100) DEFAULT '',
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  link int DEFAULT 0,
  constraint home_dash_resource_id_key PRIMARY KEY (id));

CREATE INDEX idx_resource_md5 ON resource(md5);

CREATE TABLE resource_chunk (
  id bigint NOT NULL generated by default as identity,
  chunk_number int NOT NULL,
  chunk_size int NOT NULL,
  current_chunk_size int NOT NULL,
  total_size int NOT NULL,
  identifier varchar(100) NOT NULL,
  filename varchar(100) NOT NULL,
  relative_path varchar(100) NOT NULL,
  total_chunks int NOT NULL,
  md5 varchar(32) DEFAULT '',
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  constraint home_dash_resource_chunk_id_key PRIMARY KEY (id));

CREATE INDEX idx_resource_chunk_identifier ON resource_chunk(identifier);
CREATE INDEX idx_resource_chunk_identifier_chunk ON resource_chunk(identifier, chunk_number);

-- ============================================
-- 二阶段：预览与检索整理 - 表结构
-- ============================================

CREATE TABLE file_tag (
    id bigint NOT NULL generated by default as identity,
    tag_name varchar(50) NOT NULL UNIQUE,
    tag_color varchar(20) DEFAULT '#409EFF',
    created_at timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
    updated_at timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
    constraint home_dash_file_tag_id_key PRIMARY KEY (id)
);

CREATE TABLE search_history (
    id bigint NOT NULL generated by default as identity,
    keyword varchar(200) NOT NULL,
    search_type varchar(20) DEFAULT 'FILE',
    search_params varchar(1000),
    searched_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id bigint DEFAULT NULL,
    constraint home_dash_search_history_id_key PRIMARY KEY (id)
);

CREATE INDEX idx_search_history_keyword ON search_history(keyword);
CREATE INDEX idx_search_history_searched_at ON search_history(searched_at);

CREATE TABLE favorite (
    id bigint NOT NULL generated by default as identity,
    resource_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_favorite_id_key PRIMARY KEY (id),
    constraint home_dash_favorite_resource_id_key UNIQUE (resource_id)
);

CREATE INDEX idx_favorite_created_at ON favorite(created_at);

CREATE TABLE recent_use (
    id bigint NOT NULL generated by default as identity,
    resource_id bigint NOT NULL,
    use_type varchar(20) NOT NULL,
    used_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_recent_use_id_key PRIMARY KEY (id)
);

CREATE INDEX idx_recent_use_resource_type ON recent_use(resource_id, use_type);
CREATE INDEX idx_recent_use_used_at ON recent_use(used_at);

CREATE TABLE file_remark (
    id bigint NOT NULL generated by default as identity,
    resource_id bigint NOT NULL UNIQUE,
    remark_content varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_file_remark_id_key PRIMARY KEY (id)
);

CREATE TABLE file_tag_relation (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_file_tag_relation_id_key PRIMARY KEY (id),
    constraint home_dash_file_tag_relation_unique UNIQUE (file_id, tag_id)
);

CREATE INDEX idx_file_tag_relation_file_id ON file_tag_relation(file_id);
CREATE INDEX idx_file_tag_relation_tag_id ON file_tag_relation(tag_id);

CREATE TABLE filter_view (
    id bigint NOT NULL generated by default as identity,
    view_name varchar(50) NOT NULL,
    view_params varchar(1000) NOT NULL,
    is_default boolean DEFAULT false,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_filter_view_id_key PRIMARY KEY (id)
);

CREATE INDEX idx_filter_view_name ON filter_view(view_name);

-- ============================================
-- 阶段三：媒体中心与 NAS 体验 - 表结构
-- ============================================

-- 媒体扫描任务表
CREATE TABLE media_scan_task (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL,
    media_type varchar(20) NOT NULL,
    task_type varchar(30) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    retry_count int DEFAULT 0,
    max_retries int DEFAULT 3,
    error_message varchar(500),
    priority int DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    start_time timestamp,
    finish_time timestamp,
    constraint media_scan_task_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_scan_task_status ON media_scan_task(status);
CREATE INDEX idx_media_scan_task_file_type ON media_scan_task(file_id, media_type);
CREATE INDEX idx_media_scan_task_priority ON media_scan_task(priority DESC, create_time);

-- 缩略图记录表（图片多尺寸 + 视频封面）
CREATE TABLE media_thumbnail (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL,
    thumbnail_type varchar(20) NOT NULL,
    width int,
    height int,
    thumbnail_path varchar(200) NOT NULL,
    file_size bigint,
    generate_status varchar(20) NOT NULL DEFAULT 'SUCCESS',
    generate_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_thumbnail_pk PRIMARY KEY (id),
    constraint media_thumbnail_file_type_size UNIQUE (file_id, thumbnail_type, width, height)
);

CREATE INDEX idx_media_thumbnail_file ON media_thumbnail(file_id);

-- 图片元数据表
CREATE TABLE media_picture_metadata (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL UNIQUE,
    width int,
    height int,
    taken_at timestamp,
    camera_make varchar(100),
    camera_model varchar(100),
    lens_model varchar(100),
    focal_length varchar(30),
    aperture varchar(30),
    exposure_time varchar(30),
    iso int,
    gps_latitude decimal(10, 6),
    gps_longitude decimal(10, 6),
    location_name varchar(200),
    orientation int DEFAULT 0,
    color_mode varchar(20) DEFAULT 'RGB',
    scan_status varchar(20) NOT NULL DEFAULT 'PENDING',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_picture_metadata_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_picture_taken_at ON media_picture_metadata(taken_at);
CREATE INDEX idx_media_picture_scan_status ON media_picture_metadata(scan_status);

-- 视频元数据表
CREATE TABLE media_video_metadata (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL UNIQUE,
    duration bigint,
    width int,
    height int,
    resolution varchar(20),
    bitrate bigint,
    frame_rate decimal(5, 2),
    video_codec varchar(50),
    audio_codec varchar(50),
    audio_channels int,
    audio_bitrate bigint,
    has_audio boolean DEFAULT true,
    has_subtitle boolean DEFAULT false,
    cover_generated boolean DEFAULT false,
    cover_path varchar(200),
    scan_status varchar(20) NOT NULL DEFAULT 'PENDING',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_video_metadata_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_video_scan_status ON media_video_metadata(scan_status);
CREATE INDEX idx_media_video_duration ON media_video_metadata(duration);

-- 视频系列表
CREATE TABLE media_video_series (
    id bigint NOT NULL generated by default as identity,
    series_name varchar(100) NOT NULL,
    description varchar(500),
    poster_path varchar(200),
    total_episodes int DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_video_series_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_video_series_name ON media_video_series(series_name);

-- 视频集数关联表
CREATE TABLE media_video_episode (
    id bigint NOT NULL generated by default as identity,
    series_id bigint NOT NULL,
    file_id bigint NOT NULL,
    episode_number int NOT NULL,
    season_number int DEFAULT 1,
    episode_title varchar(200),
    constraint media_video_episode_pk PRIMARY KEY (id),
    constraint media_video_episode_unique UNIQUE (series_id, episode_number, season_number)
);

CREATE INDEX idx_media_video_episode_series ON media_video_episode(series_id);
CREATE INDEX idx_media_video_episode_file ON media_video_episode(file_id);

-- 音频元数据表
CREATE TABLE media_audio_metadata (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL UNIQUE,
    title varchar(200),
    album varchar(200),
    artist varchar(200),
    album_artist varchar(200),
    genre varchar(100),
    track_number int,
    disc_number int DEFAULT 1,
    year int,
    duration bigint,
    bitrate bigint,
    sample_rate int,
    cover_path varchar(200),
    lyrics TEXT,
    scan_status varchar(20) NOT NULL DEFAULT 'PENDING',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_audio_metadata_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_audio_title ON media_audio_metadata(title);
CREATE INDEX idx_media_audio_album ON media_audio_metadata(album);
CREATE INDEX idx_media_audio_artist ON media_audio_metadata(artist);
CREATE INDEX idx_media_audio_scan_status ON media_audio_metadata(scan_status);

-- 播放列表表
CREATE TABLE media_audio_playlist (
    id bigint NOT NULL generated by default as identity,
    playlist_name varchar(100) NOT NULL,
    description varchar(500),
    cover_path varchar(200),
    play_mode varchar(20) DEFAULT 'ORDER',
    total_tracks int DEFAULT 0,
    total_duration bigint DEFAULT 0,
    is_default boolean DEFAULT false,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_audio_playlist_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_audio_playlist_name ON media_audio_playlist(playlist_name);

-- 播放列表曲目关联表
CREATE TABLE media_audio_playlist_item (
    id bigint NOT NULL generated by default as identity,
    playlist_id bigint NOT NULL,
    file_id bigint NOT NULL,
    position int NOT NULL,
    added_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_audio_playlist_item_pk PRIMARY KEY (id),
    constraint media_audio_playlist_item_unique UNIQUE (playlist_id, file_id)
);

CREATE INDEX idx_media_audio_playlist_item_playlist ON media_audio_playlist_item(playlist_id);
CREATE INDEX idx_media_audio_playlist_item_position ON media_audio_playlist_item(playlist_id, position);

-- 相册表
CREATE TABLE media_album (
    id bigint NOT NULL generated by default as identity,
    album_name varchar(100) NOT NULL,
    album_type varchar(20) NOT NULL DEFAULT 'AUTO',
    cover_file_id bigint,
    description varchar(500),
    rule_expression varchar(200),
    photo_count int DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_album_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_album_type ON media_album(album_type);
CREATE INDEX idx_media_album_name ON media_album(album_name);

-- 相册与图片关联表
CREATE TABLE media_album_item (
    id bigint NOT NULL generated by default as identity,
    album_id bigint NOT NULL,
    file_id bigint NOT NULL,
    taken_at timestamp,
    sort_order int,
    added_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_album_item_pk PRIMARY KEY (id),
    constraint media_album_item_unique UNIQUE (album_id, file_id)
);

CREATE INDEX idx_media_album_item_album ON media_album_item(album_id);
CREATE INDEX idx_media_album_item_file ON media_album_item(file_id);
CREATE INDEX idx_media_album_item_taken ON media_album_item(album_id, taken_at);

-- 播放历史表（视频+音频通用）
CREATE TABLE play_history (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL,
    media_type varchar(20) NOT NULL,
    play_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    play_duration bigint,
    constraint play_history_pk PRIMARY KEY (id)
);

CREATE INDEX idx_play_history_file ON play_history(file_id);
CREATE INDEX idx_play_history_time ON play_history(play_time DESC);

-- 视频观看进度表（支持继续播放）
CREATE TABLE watch_progress (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL UNIQUE,
    current_position bigint NOT NULL DEFAULT 0,
    duration bigint NOT NULL,
    progress_percent decimal(5, 2) GENERATED ALWAYS AS (CASE WHEN duration > 0 THEN (current_position * 100.0 / duration) ELSE 0 END) STORED,
    finished boolean DEFAULT false,
    last_watched timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint watch_progress_pk PRIMARY KEY (id)
);

CREATE INDEX idx_watch_progress_file ON watch_progress(file_id);
CREATE INDEX idx_watch_progress_percent ON watch_progress(progress_percent);

-- 字幕关联表
CREATE TABLE subtitle (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL,
    subtitle_path varchar(200) NOT NULL,
    language varchar(10) NOT NULL,
    subtitle_type varchar(20) NOT NULL DEFAULT 'EXTERNAL',
    format varchar(10) NOT NULL DEFAULT 'SRT',
    is_default boolean DEFAULT false,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint subtitle_pk PRIMARY KEY (id)
);

CREATE INDEX idx_subtitle_file ON subtitle(file_id);
CREATE INDEX idx_subtitle_language ON subtitle(file_id, language);

-- 首页聚合缓存表
CREATE TABLE media_summary_cache (
    id bigint NOT NULL generated by default as identity,
    cache_key varchar(50) NOT NULL UNIQUE,
    cache_value TEXT NOT NULL,
    expire_time timestamp NOT NULL,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint media_summary_cache_pk PRIMARY KEY (id)
);

CREATE INDEX idx_media_summary_cache_key ON media_summary_cache(cache_key);
CREATE INDEX idx_media_summary_cache_expire ON media_summary_cache(expire_time);
