CREATE SCHEMA home_dash AUTHORIZATION home_dash;

CREATE TABLE file (
  id bigint NOT NULL generated by default as identity,
  file_name varchar(100) NOT NULL,
  parent_id bigint NOT NULL DEFAULT 0,
  type varchar(45) NOT NULL,
  size bigint DEFAULT 0,
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  resource_id bigint DEFAULT NULL,
  constraint home_dash_file_id_key PRIMARY KEY (id));

CREATE INDEX index2 ON file(parent_id, file_name);

CREATE TABLE resource (
  id bigint NOT NULL generated by default as identity,
  size bigint DEFAULT 0,
  md5 varchar(32) DEFAULT '',
  path varchar(100) DEFAULT '',
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  link int DEFAULT 0,
  constraint home_dash_resource_id_key PRIMARY KEY (id));

-- 为resource表的md5字段创建索引，优化秒传查询性能
CREATE INDEX idx_resource_md5 ON resource(md5);

CREATE TABLE resource_chunk (
  id bigint NOT NULL generated by default as identity,
  chunk_number int NOT NULL,
  chunk_size int NOT NULL,
  current_chunk_size int NOT NULL,
  total_size int NOT NULL,
  identifier varchar(100) NOT NULL,
  filename varchar(100) NOT NULL,
  relative_path varchar(100) NOT NULL,
  total_chunks int NOT NULL,
  md5 varchar(32) DEFAULT '',
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  constraint home_dash_resource_chunk_id_key PRIMARY KEY (id));

-- 为resource_chunk表添加索引，优化分块查询性能
CREATE INDEX idx_resource_chunk_identifier ON resource_chunk(identifier);
CREATE INDEX idx_resource_chunk_identifier_chunk ON resource_chunk(identifier, chunk_number);

-- ============================================
-- 二阶段：预览与检索整理 - 表结构
-- ============================================

-- 标签表：用于文件分类标签
CREATE TABLE file_tag (
    id bigint NOT NULL generated by default as identity,
    tag_name varchar(50) NOT NULL UNIQUE,
    tag_color varchar(20) DEFAULT '#409EFF',
    created_at timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
    updated_at timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
    constraint home_dash_file_tag_id_key PRIMARY KEY (id)
);

-- 搜索历史表：记录用户搜索关键词
CREATE TABLE search_history (
    id bigint NOT NULL generated by default as identity,
    keyword varchar(200) NOT NULL,
    search_type varchar(20) DEFAULT 'FILE',
    search_params varchar(1000),
    searched_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_search_history_id_key PRIMARY KEY (id)
);

CREATE INDEX idx_search_history_keyword ON search_history(keyword);
CREATE INDEX idx_search_history_searched_at ON search_history(searched_at);

-- 收藏表：记录用户收藏的文件
CREATE TABLE favorite (
    id bigint NOT NULL generated by default as identity,
    resource_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_favorite_id_key PRIMARY KEY (id),
    constraint home_dash_favorite_resource_id_key UNIQUE (resource_id)
);

CREATE INDEX idx_favorite_created_at ON favorite(created_at);

-- 最近使用表：记录用户最近访问的文件
CREATE TABLE recent_use (
    id bigint NOT NULL generated by default as identity,
    resource_id bigint NOT NULL,
    use_type varchar(20) NOT NULL,
    used_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_recent_use_id_key PRIMARY KEY (id)
);

CREATE INDEX idx_recent_use_resource_type ON recent_use(resource_id, use_type);
CREATE INDEX idx_recent_use_used_at ON recent_use(used_at);

-- 文件备注表：用户对文件的备注信息
CREATE TABLE file_remark (
    id bigint NOT NULL generated by default as identity,
    resource_id bigint NOT NULL UNIQUE,
    remark_content varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_file_remark_id_key PRIMARY KEY (id)
);

-- 文件-标签关联表：文件和标签的多对多关系
CREATE TABLE file_tag_relation (
    id bigint NOT NULL generated by default as identity,
    file_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_file_tag_relation_id_key PRIMARY KEY (id),
    constraint home_dash_file_tag_relation_unique UNIQUE (file_id, tag_id)
);

CREATE INDEX idx_file_tag_relation_file_id ON file_tag_relation(file_id);
CREATE INDEX idx_file_tag_relation_tag_id ON file_tag_relation(tag_id);

-- 筛选视图保存表：用户保存的常用筛选条件
CREATE TABLE filter_view (
    id bigint NOT NULL generated by default as identity,
    view_name varchar(50) NOT NULL,
    view_params varchar(1000) NOT NULL,
    is_default boolean DEFAULT false,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    constraint home_dash_filter_view_id_key PRIMARY KEY (id)
);

CREATE INDEX idx_filter_view_name ON filter_view(view_name);
